### ISSUE TITLE
Update readme with how to use

### ISSUE THREAD

**Issue by abdullacm** [teqnomaze/pckapi#1]
Can you update the readme with how to use or include a sample file.

Thanks,

**Comment by musthafasm** [comment]
This is only a class library for using with SOAP server classMap. You can use this library to map each SOAP functions and it's parameters calling from PCKasse.

### Example usage

```

function createWebshop(\Teqnomaze\Pckapi\V1\Request\CreateWebshop $param)
{
   // Do your stuff and return proper SOAP response
    return $response;
}

const CLASS_MAP = array(
	'createWebshop' => \Teqnomaze\Pckapi\V1\Request\CreateWebshop::class,
	'webCompany' => \Teqnomaze\Pckapi\V1\Struct\WebCompany::class
);

$server = new \SoapServer( null, array(
	'soap_version' => SOAP_1_1,
	'classmap'       => CLASS_MAP,
) );

$server-> addFunction('createWebshop');
$server->handle();
```

**Comment by abdullacm** [comment]
@musthafasm thanks for your response, im trying to integrate pckasse with an ecommerce. I was looking for php library, found this. Let me try as you have explained.

Thanks for your support.

**Comment by abdullacm** [comment]
@musthafasm 

i could not find folder name Request

Pckapi\V1\Request

i can see 
Pckapi\V1\Request\Struct
Pckapi\V1\Request\Response


can you show the sample of how the response (what should be the actual value for $response) is returned with this function

function createWebshop(\Teqnomaze\Pckapi\V1\Request\CreateWebshop $param)
{
   // Do your stuff and return proper SOAP response
    return $response;
}
